/* This file has been autogenerated from 'test01.idl'. */
/* Generator component: $Id: c-constraints-backend.c,v 1.2 2004/11/19 10:00:34 perez Exp $ */
/* You can customize this file to your needs */

static const char gs_generator[]="$Id: c-constraints-backend.c,v 1.2 2004/11/19 10:00:34 perez Exp $";

#include <string>
#include "test01_constraints.h"


using namespace std;


string Subst_constraints(file referenceCFG, double seed)
{
   return "true";
}


double Subst_cost(file referenceCFG, double seed)
{
   return 1.0;
}


void Subst_description(int *numCPUs, char **jobType , file referenceCFG, double seed)
{
   *numCPUs = 1;
   *jobType = "sequential";
}


string Dimem_constraints(file newCFG, file traceFile)
{
   return "true";
}


double Dimem_cost(file newCFG, file traceFile)
{
   return 1.0;
}


void Dimem_description(int *numCPUs, char **jobType , file newCFG, file traceFile)
{
   *numCPUs = 1;
   *jobType = "sequential";
}


string Post_constraints(file newCFG, file DimemasOUT, file FinalOUT)
{
   return "true";
}


double Post_cost(file newCFG, file DimemasOUT, file FinalOUT)
{
   return 1.0;
}


void Post_description(int *numCPUs, char **jobType , file newCFG, file DimemasOUT, file FinalOUT)
{
   *numCPUs = 1;
   *jobType = "sequential";
}


