/* This file must be #included in the actual implementation file. */
/* This file has been autogenerated from 'test01.idl'. */
/* Generator component: $Id: c-backend.c,v 1.11 2004/11/19 10:00:34 perez Exp $ */
/* CHANGES TO THIS FILE WILL BE LOST */

#ifndef _GSS_TEST01_H
#define _GSS_TEST01_H

#ifdef __cplusplus
extern "C" {
#endif

/* The actual functions must use this variable to return their error codes */
extern int gs_result;

typedef char* file;

enum operationCode {SubstOp, DimemOp, PostOp};

/* Functions to be implemented. We sugest that you create a file */
/* with name 'test01-functions.c' and implement them there. */
void Subst(file referenceCFG, double seed, double * newCFG);
void Dimem(file newCFG, file traceFile, file DimemasOUT);
void Post(file newCFG, file DimemasOUT, file FinalOUT);

#ifdef __cplusplus
}
#endif

#endif /* _GSS_TEST01_H */
