/* This file has been autogenerated from 'test01.idl'. */
/* Generator component: $Id: c-constraints-backend.c,v 1.2 2004/11/19 10:00:34 jorgee Exp $ */
/* CHANGES TO THIS FILE WILL BE LOST */

#ifndef _GSS_TEST01_CONSTRAINTS_H
#define _GSS_TEST01_CONSTRAINTS_H

#include <string>

using namespace std;
typedef char* file;

/* Functions to be implemented in file 'test01_constraints.cc'. */

string Subst_constraints(file referenceCFG, double seed);
double Subst_cost(file referenceCFG, double seed);
void Subst_description(int *numCPUs, char **jobType , file referenceCFG, double seed);
string Dimem_constraints(file newCFG, file traceFile);
double Dimem_cost(file newCFG, file traceFile);
void Dimem_description(int *numCPUs, char **jobType , file newCFG, file traceFile);
string Post_constraints(file newCFG, file DimemasOUT, file FinalOUT);
double Post_cost(file newCFG, file DimemasOUT, file FinalOUT);
void Post_description(int *numCPUs, char **jobType , file newCFG, file DimemasOUT, file FinalOUT);

#endif /* _GSS_TEST01_CONSTRAINTS_H */
